table dimProductCategory
	lineageTag: 4e43a0f6-6f6c-48d6-802e-5f9cebc6e9b5

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 8789295a-e862-4356-935e-4446a72a89f1
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductCategoryAlternateKey
		dataType: int64
		formatString: 0
		lineageTag: 9639a1dc-bb80-4f13-a273-0b9744a254fe
		summarizeBy: none
		sourceColumn: ProductCategoryAlternateKey

		annotation SummarizationSetBy = Automatic

	column EnglishProductCategoryName
		dataType: string
		lineageTag: 8b7b3174-1262-4082-8c24-db89d80926d3
		summarizeBy: none
		sourceColumn: EnglishProductCategoryName

		annotation SummarizationSetBy = Automatic

	column SpanishProductCategoryName
		dataType: string
		lineageTag: 2da1e344-ae25-48fb-8af9-98127785b5ba
		summarizeBy: none
		sourceColumn: SpanishProductCategoryName

		annotation SummarizationSetBy = Automatic

	column FrenchProductCategoryName
		dataType: string
		lineageTag: d9abfc14-3322-4f3b-90d9-f2c34e34241a
		summarizeBy: none
		sourceColumn: FrenchProductCategoryName

		annotation SummarizationSetBy = Automatic

	partition dimProductCategory = m
		mode: import
		source =
				let
				    Origen = PowerPlatform.Dataflows(null),
				    Workspaces = Origen{[Id="Workspaces"]}[Data],
				    #"2df341fb-8872-49e3-a06d-321c2fb40639" = Workspaces{[workspaceId="2df341fb-8872-49e3-a06d-321c2fb40639"]}[Data],
				    #"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420" = #"2df341fb-8872-49e3-a06d-321c2fb40639"{[dataflowId="b9c8fcd9-6d0a-42f4-9adb-ecee6e728420"]}[Data],
				    dimProductCategory_ = #"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420"{[entity="dimProductCategory",version=""]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(dimProductCategory_, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ProductCategoryKey", Int64.Type}, {"ProductCategoryAlternateKey", Int64.Type}, {"EnglishProductCategoryName", type text}, {"SpanishProductCategoryName", type text}, {"FrenchProductCategoryName", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

