table dimProductSubCategory
	lineageTag: 1457683b-4856-429a-8908-323b0f475a68

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: a5acf546-669b-4122-b2fd-79ecae51d459
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryAlternateKey
		dataType: int64
		formatString: 0
		lineageTag: 0be037be-68d3-410a-9dec-6f3d7f7283c4
		summarizeBy: count
		sourceColumn: ProductSubcategoryAlternateKey

		annotation SummarizationSetBy = Automatic

	column EnglishProductSubcategoryName
		dataType: string
		lineageTag: 34ce0470-d6c7-4331-9968-2e2ef3c12dbd
		summarizeBy: none
		sourceColumn: EnglishProductSubcategoryName

		annotation SummarizationSetBy = Automatic

	column SpanishProductSubcategoryName
		dataType: string
		lineageTag: c6b2ebb8-439b-4f3b-9681-8456bcde3e09
		summarizeBy: none
		sourceColumn: SpanishProductSubcategoryName

		annotation SummarizationSetBy = Automatic

	column FrenchProductSubcategoryName
		dataType: string
		lineageTag: 66903196-dafa-499d-8a16-ed1b43b5bd30
		summarizeBy: none
		sourceColumn: FrenchProductSubcategoryName

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: cb6a3438-21b4-42db-bf16-781fa6048476
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	partition dimProductSubCategory = m
		mode: import
		source =
				let
				    Origen = PowerPlatform.Dataflows(null),
				    Workspaces = Origen{[Id="Workspaces"]}[Data],
				    #"2df341fb-8872-49e3-a06d-321c2fb40639" = Workspaces{[workspaceId="2df341fb-8872-49e3-a06d-321c2fb40639"]}[Data],
				    #"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420" = #"2df341fb-8872-49e3-a06d-321c2fb40639"{[dataflowId="b9c8fcd9-6d0a-42f4-9adb-ecee6e728420"]}[Data],
				    dimProductSubCategory_ = #"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420"{[entity="dimProductSubCategory",version=""]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(dimProductSubCategory_, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ProductSubcategoryKey", Int64.Type}, {"ProductSubcategoryAlternateKey", Int64.Type}, {"EnglishProductSubcategoryName", type text}, {"SpanishProductSubcategoryName", type text}, {"FrenchProductSubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

